### ISSUE TITLE
meet segmentation fault when training LINE

### ISSUE THREAD

**Issue by kenwu90** [tangjianpku/LINE#9]
hi,

I have tried to train LINE with -train ../../text_article_product_pair.txt -output 2_order_embedding_file -size 200 -order 2 -negative 5 -samples 100 -rho 0.025 -threads 20

and I got the following from gdb
============================================================
Program received signal SIGSEGV, Segmentation fault.
_int_malloc (av=av@entry=0x7ffff7203760 <main_arena>, bytes=bytes@entry=10) at malloc.c:3775
3775    malloc.c: No such file or directory.
(gdb) bt
#0  _int_malloc (av=av@entry=0x7ffff7203760 <main_arena>, bytes=bytes@entry=10) at malloc.c:3775
#1  0x00007ffff6ec51ec in __libc_calloc (n=<optimized out>, elem_size=<optimized out>) at malloc.c:3219
#2  0x00000000004013ad in AddVertex (name=0x7fffffffb890 “春新神“) at line.cpp:101
#3  0x0000000000401772 in ReadData () at line.cpp:161
#4  0x0000000000402996 in TrainLINE () at line.cpp:391
#5  0x0000000000402f42 in main (argc=17, argv=0x7fffffffe228) at line.cpp:465

=============================================================
and following from valgrind
===============================================================
valgrind: m_mallocfree.c:304 (get_bszB_as_is): Assertion ‘bszB_lo == bszB_hi’ failed.
valgrind: Heap block lo/hi size mismatch: lo = 176, hi = 7598532953432678760.
This is probably caused by your program erroneously writing past the
end of a heap block and corrupting heap metadata.  If you fix any
invalid writes reported by Memcheck, this assertion failure will

=================================================================

could you have a look about this issue?

Thank you
Ken

**Comment by kenwu90** [comment]
fixed the bug and provide a pull request. plz check
https://github.com/tangjianpku/LINE/pull/10
